### ISSUE TITLE
[Feature Request] Allow compilation of .razor.scss files into .razor.css files but always saving them in the same path they are found

### ISSUE THREAD

**Issue by scott-parkhill** [glenn2223/vscode-live-sass-compiler#115]
Working with Blazor, they have CSS isolation. So you can have your `some_page.razor` page and have all its relevant styling in the `some_page.razor.css` file. However, this `.razor.css` file **must** be in the same directory as the `some_page.razor` file and **must** have the same name. I have defined some `some_page.razor.scss` files and then manually compile them so they can stay in the same folder as the base razor page. I have then excluded all the folders that contain razor pages from the live sass compiler, because otherwise they are found and end up in our complied CSS folder, and then Blazor throws an error because it finds a `some_page.razor.css` file without an accompanying `some_page.razor` file in the same directory. It would be really nice if this compiler could compile `.razor.scss` files "in-place".

Thank you!

**Comment by glenn2223** [comment]
By default, the compiler will save to the same location of the `.scss` file it's compiling. This means that as long as the `.scss` file is in with your `.razor` file then so will the `.css` file it compiles.

The only part that I'm finding somewhat confusing is:
> I have then excluded all the folders that contain razor pages from the live sass compiler, because otherwise they are found and end up in our complied CSS folder

Do you have normal SCSS files that you compile to a different location (i.e. `/assets/scss/` to `/assets/css/`) as well as the various razor pages with it's accompanying SCSS & CSS files?

If so, I believe there are currently two solutions

1. Change the settings so the file outputs in the same location as the SCSS file - so remove `savePath`, or set it to null
2. Or, alternatively, add the razor pages folder to your workspace as a new workspace folder. This can then have it's own independent settings and you can exclude the `/Pages` folder from the main settings file - something like [Issue 115.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/6992833/Issue.115.zip)

**Comment by scott-parkhill** [comment]
Hi Glenn, thank you for your response. I'm not sure what you mean exactly by creating a new workspace for the razor files. We currently have our SCSS broken out according to different use cases, which are then all imported in a `main.scss` file which we then compile to `main.css`. So we have like `wwwroot/css/compiled/` where that `main.css` file goes, and then things like `wwwroot/scss/base`, `wwwroot/scss/components`, `wwwroot/scss/pages`, etc. In total we have nearly 20 `.scss` files that are then imported into `main.scss` and compiled to one place, `main.css`, by design.

That is why I have to exclude to razor folders `**/Shared/**` and `**/Pages/**` because otherwise the `.razor.scss` files end up in the `wwwroot/compiled/` directory. I'm not sure what you mean by creating the new work space or if this is feasible at this point in the project.

**Comment by glenn2223** [comment]
Hey @scott-parkhill,

Sorry for the delay. This is quite a niche so I don't think it's a feature that is really required, especially as the save path routing is already so varied. Plus there would be so many edge cases, those excluded save paths may require different save locations for each, not to be defaulted to saving to the same location as its SCSS file.

May I suggest that you move `main.scss` to `/wwwroot/compiled` and change your links within it. Then all you need to do is remove the `savePath` setting and then all files will save to the folder that its SCSS file is in.

Alternatively, you may be able to utilise the "relative to file" feature - though I'd imagine it would still require some directory/file reshuffling. For example, `~/../` will save relative to the current file, just up one folder in the hierarchy.

---

FYI: Workspaces can be added to a project at any time - ref the below screenshot. Just right click on some open space in the explorer. Once you do this you will need to make sure you open the workspace file instead of the folder itself (when you close the project you will be asked to save the workspace configuration file - I usually save it in the `/.vscode` folder)

![image](https://user-images.githubusercontent.com/33450392/130042495-ad945d47-8b71-4157-b318-50ec7791497b.png)

You would then add the `Pages` folder to your workspace and have its own custom settings - my project, as an example, is here:
[Issue 115 - Workspace example.zip](https://github.com/glenn2223/vscode-live-sass-compiler/files/7013263/Issue.115.-.Workspace.example.zip) - just open the `/.vscode/My Special Workspace Name.code-workspace` file to see it in action


You can see the result from the screenshot below

![image](https://user-images.githubusercontent.com/33450392/130042992-36f1ea3b-ce0d-410f-b116-d68666014dd1.png)

---

I will close for now. However, if this is a heavily requested feature, I will review it again. Anyone else, please 👍 to show support for this feature request

Please also continue to comment @scott-parkhill, if you still have questions or need more help

**Comment by scott-parkhill** [comment]
@glenn2223 That's really good to know about workspaces! Thank you! Will probably give this a shot. If I wanted to poke around the code to add this feature myself, would you accept a PR for it? And if so, do you know what files I should start looking at?

**Comment by glenn2223** [comment]
Sorry for the delay, been crazy busy recently.

>That's really good to know about workspaces! Thank you!

No problem, glad to share the knowledge 😁

>If I wanted to poke around the code to add this feature myself, would you accept a PR for it? And if so, do you know what files I should start looking at?

To be honest, probably not. It seems like such an edge case. However, if others require the same feature then I would be open to adding it. There's just so many alternate solutions currently - as stated previously - that I don't see there being much of a requirement.

However, don't let me stop you from creating your own fork and adding your own custom functionality. You'd have to add the setting to the `package.json` file and then wrap [this](https://github.com/glenn2223/vscode-live-sass-compiler/blob/0cd110c2173a58def4fd53c3350bd4b40766f43a/src/appModel.ts#L525-L598) in an if statement - after getting the users setting input - in order to add the functionality.
