### ISSUE TITLE
When using Live Share updates are not seen

### ISSUE THREAD

**Issue by ctsstc** [glenn2223/vscode-live-sass-compiler#151]
When someone on live share edits a `sass` file it does not seem to get picked up as a changed file, I have to go into the file and save it myself to get it to trigger.

The other person also has the extension installed and gets the following error on their side:

```
Compilation Error
Error: src/client/css/base.sass: no such file or directory
```

Edit: if I stay in the `sass` file with him he is able to save from his side and it will pick up on the changes and recompile. I tried keeping the file open in a split view tab but that does not seem to work.

**Comment by glenn2223** [comment]
The extension is set up so that when _you_ save a file it checks if that file is a Sass file and then compiles it. As you are not directly saving the file vscode doesn't know it needs to trigger my extension.

With you having the file open directly it may apply the change as a save to keep your system up to date with the latest edit/revision.

The other user may be getting the error as the files are not local. Though I'm not sure.

I will check the live share code and see how it works. I'll also check see if the expected behaviour is even possible in this scenario.

Please be aware that this might not even be possible

**Comment by ctsstc** [comment]
This may potentially be a bug/feature request that I need to throw in for VSCode. I haven't dug into extension support for VS Live Share.

**Comment by glenn2223** [comment]
Any luck @ctsstc

**Comment by glenn2223** [comment]
Hey @ctsstc,

Did you have any luck with the build?

**Comment by glenn2223** [comment]
Closing as awaiting feedback
