### ISSUE TITLE
Terminal pops up anytime I make a change in any .scss file. 

### ISSUE THREAD

**Issue by Xteripus** [glenn2223/vscode-live-sass-compiler#158]
Is there any way to prevent this?

Thank you for upgrading the extension by the way, amazing work.

**Comment by glenn2223** [comment]
Yes, you need to change the `liveSassCompile.settings.showOutputWindowOn` setting. I'd recommend using `Warning` as this only pops up when there is an error or warning with your SASS.

Let me know if this works for you

**Comment by Xteripus** [comment]
Works like a charm! Thank you for fast response. 
Also I am getting a warning from here, I was using out-dated sass extension just switched to yours today.
Here is the warning:
![image](https://user-images.githubusercontent.com/68998228/157630196-b89b2b01-9b1a-4eb2-93b0-7a1fb05bbc47.png)

**Comment by glenn2223** [comment]
To unify the format of settings, all settings that are intended to have file/folder paths need to start with a leading slash (`/` or `\`, depending on your platform/preference). However, this isn't necessary in order to compile your SASS files

In your case, you just need to add a `/` at the start of each line. However, you seem to have the default setting so you can just remove that setting completely - if you like 🤷‍♂️

I hope this makes sense

----

Closing but please continue to ask any more questions you have 😁

**Comment by Xteripus** [comment]
Thanks a lot! Again, amazing work!
