### ISSUE TITLE
Compiler Unexpectedly Removing some CSS rules.

### ISSUE THREAD

**Issue by HJPoyntz** [glenn2223/vscode-live-sass-compiler#212]
For some reason the compiler upon running the : `live sass compile current sass file` command from VSCode it is unexpectedly removing multiple CSS rules. 

Mainly -webkit CSS rules. However it is also removing others such as -moz, -ms and a few others

This is after running the compiler in VSCode:
![Screenshot 2022-08-05 at 16 26 54](https://user-images.githubusercontent.com/87074073/183109957-2489f740-2c1d-486c-a93e-e7fbec478af2.png)
.

The same file compiles as expected using  https://sass-lang.com/install

(installed on a mac using brew install sass/sass/sass )

We are using version 1.54.0 

Thank you 👍

**Comment by glenn2223** [comment]
Please see #165

Side bar: Sass doesn't do any prefixing which is why prefixes aren't touched/removed

---

Closing as duplicate

**Comment by Brockenstein** [comment]
prefixes are definitely removed during the output of the css

**Comment by glenn2223** [comment]
Sorry, my previous comment wasn't clear.

I was trying to explain that it you are to use just the SASS package, available at the link provided earlier, the prefixes will not be touched - which is why they said their prefixes weren't removed, in this case. This is because the SASS package by itself does not do anything with prefixing. It just takes the SASS and turns it into CSS.

However, my extension is bundled with autoprefix. So, when the file is then run through that, it will remove and unnecessary prefixes and add any required ones. 

The reason I linked to #165 was to highlight that most prefixes aren't actually required now. Browser support for these things has improved significantly! This means that most prefixes aren't actually required today - with a bigger win of smaller file sizes!

But yes you can configure the autoprefix setting to still include these prefixes. This can be done by saying that you still want to support a dead browser or specific browser too . Now, `display: flex` only needs a prefix for IE, which is out of support - so your shouldn't really be targeting a vulnerable and un-updated browser in my opinion. Oh you can checkout [this section](https://youtube.com/watch?v=6Wo3mYBLNyA&t=1330s) of the YouTube video for more help with this setting
