### ISSUE TITLE
"@extent" instead of "@extend" and incomplete line of code is processed as success

### ISSUE THREAD

**Issue by RazaNaqsh** [glenn2223/vscode-live-sass-compiler#255]
![Screenshot from 2023-01-18 07-22-08](https://user-images.githubusercontent.com/108403182/213062343-2be2793d-0ea8-41d0-920f-bb9f583abf53.png)

**Comment by glenn2223** [comment]
The extension returns a success state because the SASS compilation was successful. Which, as you can see below, is correct. It has compiled the output and the line of code is there - it's just output **_as-is_** rather than using any SASS features.

![image](https://user-images.githubusercontent.com/33450392/213148048-9b9dc952-8837-48fe-bc33-01bba5c0664f.png)

---

If you want it to throw an error then you'd have to make a feature request/bug report over at [sass/dart-sass](https://github.com/sass/dart-sass). However, from the below link - I doubt it will be accepted

https://sass-lang.com/documentation/at-rules/function#plain-css-functions
