### ISSUE TITLE
"useNewCompiler": true > Doesn't recompile files via @include meta.load-css("...");

### ISSUE THREAD

**Issue by Jugibur** [glenn2223/vscode-live-sass-compiler#307]
Hi,
I am surprised that when using the new compiler with the appropriate setting, the error occurs that files included via meta.load-css() are not taken into account for recompiling.
This was a bug in Dart Sass before version 1.58 as stated here:
https://github.com/sass/dart-sass/blob/main/CHANGELOG.md#1580

So actually it should be the other way around, because if I use version 6.0.6 with DartSass 1.62.1, the bug should be fixed with this new compiler - or where is my thinking error? Or does "useNewCompiler" mean something different? 
Thanks in advance!

**Comment by glenn2223** [comment]
`useNewCompiler` just uses the new JS API (the `compile(...)` method, rather than the legacy `compiler.renderSync(...)`). This extension has never used the inbuilt watcher.

Watching is taken care of by VS Code file change tracking, which triggers my code to compile (if necessary) - which you can see below:
https://github.com/glenn2223/vscode-live-sass-compiler/blob/c37e4e2915b6255362a3a2adc1d9b4ac521b3623/src/extension.ts#L173-L181

**Comment by glenn2223** [comment]
Sorry, to clarify: it doesn't error when `useNewCompiler` is false - but does when it's true?

Could I see the SASS file?

**Comment by Jugibur** [comment]
I just created a reduced demo and – regardless of the "useNewCompiler" setting – found that it works there (of course). So it has something to do with the constellations in my project and possibly with the many plugins and settings that interfere with each other. Sorry for the false alarm, so I'm closing this case. Thanks for your engagement!

**Comment by glenn2223** [comment]
Thanks for doing the extra digging and confirming the false alarm. Glad you've made progress and hope you can resolve it soon

Feel free to come back to me if you do find any weirdness with the extension as you move forward 😁
