### ISSUE TITLE
Live Sass stuck in "Working on it"

### ISSUE THREAD

**Issue by OmegaER** [glenn2223/vscode-live-sass-compiler#332]
![Screenshot 2023-10-09 130041](https://github.com/glenn2223/vscode-live-sass-compiler/assets/34311633/279db394-2f10-4684-8fc4-6c9d66ba6a56)

Hello, I'm not sure if I showed the correct process for this bug, but the "Watch Sass" function stopped working today. Let me know if you need something else to look at this problem.
Kind regards.

**Comment by OmegaER** [comment]
P.S.: I noticed the system crashes with "@while" and I have the same problem with Prepros.

**Comment by glenn2223** [comment]
Though I haven't tested it; I think you need to move the `$p : $p + 1;` outside the class. I think, rather than incrementing, it's just writing the same value over and over (and hanging)

**Comment by OmegaER** [comment]
This is what I'm trying, though it doesn't work either. Not sure if this was the way it was supposed to be.
![Screenshot 2023-10-09 152414](https://github.com/glenn2223/vscode-live-sass-compiler/assets/34311633/774dd014-754b-4e38-bed0-c8ba813b9c22)

Also, I'm basically trying to reproduce the outcome from this tutorial.
![Screenshot 2023-10-09 152501](https://github.com/glenn2223/vscode-live-sass-compiler/assets/34311633/f0cfe0b1-d25e-49cb-a781-6a879caf165d)

**Comment by glenn2223** [comment]
As I said it's not actually incrementing the variable. So the tutorial needs updating/correcting

Here is a tweak to your code that shows that no incrementing is happening
![image](https://github.com/glenn2223/vscode-live-sass-compiler/assets/33450392/0a24d08b-a7c5-4636-a534-25751ff9905d)

It's only because my `$i` variable is outside the class that it's incrementing and breaking the loop

---

As for the hanging issue. I always wanted to introduce a "kill" function to the extension that means long running (possibly infinite) compilations can be terminated. I have an idea, but need to investigate. For now this will be closed as "user-error" tag
