### ISSUE TITLE
Bug: generated source maps don't point to the exact line but to the parent selector

### ISSUE THREAD

**Issue by idChef** [glenn2223/vscode-live-sass-compiler#71]
Hi, I have this issue that keeps bothering me on my bigger project. I have a lot of media queries in selectors and I need to be able to jump quickly to the line it is written at but source maps reference me to the parent selector. 

So basically there is something wrong with how source maps are generated.

//EDIT
I think it has something to do with mixins in scss.

**Comment by glenn2223** [comment]
I'm afraid that this is out of scope. Maps, by default, have always linked to the actual CSS selector and not the line, as per the below figure.

*Chrome handling a CSS file mapping automatically, as there is no map file; this links it to the sector, not the style*  
![Chrome handling a CSS file mapping automatically, as there is no map file; this links it to the sector, not the style](https://user-images.githubusercontent.com/33450392/115850663-04b6e000-a41e-11eb-9f60-512764785d04.png)

At the end of the day, maps are for a CSS file and not a SASS file. All the map needs to know is that "***this selector*** can be found at `this line`". Not "***this selector*** is made up of code at `this line`, `that line` and `this other line`". 

When SASS interoperates the file, all it says is "actually... you need to look at `this file` and `this line` for ***this selector***".

To implement a change like this SASS would need to go from mapping a single selector to mapping the selectors and the various sources of every single style. Plus browsers would need to know how to handle this array of information.

Leading on, if you wanted this feature then you'd probably be better doing a feature request with the devs at [SASS themselves](https://github.com/sass/dart-sass). They'd then have to try and change the official specification - that browsers would then have to implement. Again, they might also say this is out of scope because the file size will increase dramatically to handle every line of CSS as opposed to each selector.
